- name: Run command in pods 
  hosts: all
  tasks: 
    
    - name: Obter o nome do pod dinamicamente e executar comand
      shell: | 
        pod_name=$(sudo kubectl get pods -l app=nginx -o jsonpath='{.items[0].metadata.name}')
        sudo kubectl exec -it $pod_name -- {{COMAND}}  
      args:
        executable: /bin/bash
     
    
     