- name: Run command in pods 
  hosts: all
  tasks: 
   
    
    - name: Obter o nome do pod dinamicamente e executar comand
      shell: | 
        kubectl version
 
      args:
        executable: /bin/bash
    
     