- name: Run command in pods 
  hosts: all
  tasks: 
   
    
    - name: Obter o nome do pod dinamicamente e executar comand
      shell: | 
        kubectl cluster-info --context kind-kind 
 
      args:
        executable: /bin/bash
    
     