- name: Run command in pods 
  hosts: all
  tasks: 

    - name: lookup secretsmanager secret in the current region
      set_fact: 
        secret_value: "{{ lookup('aws_ssm', 'ACCESS_AWS', region='us-east-1')}}"
        secret_value2: "{{lookup('aws_ssm',  'SECRET_AWS', region='us-east-1')}}"
        
    - name: configure aws 
      shell: |
         aws configure set aws_access_key_id  {{ secret_value }}
         aws configure set aws_secret_access_key {{ secret_value2 }}
         aws eks --region us-east-1 update-kubeconfig --name  {{CLUSTER_NAME}}
      args:
        executable: /bin/bash

    - name: view valor
      debug:
        var: secret_value