- name: Run command in pods 
  hosts: all
  tasks: 

    - name: lookup secretsmanager secret in the current region
      set_fact: 
        secret_value: "{{ lookup('aws_ssm', 'ACCESS_AWS', region='us-east-1')}}"
        secret_value2: "{{lookup('aws_ssm',  'SECRET_AWS', region='us-east-1')}}"
        
    - name: configure aws 
      shell: |
         aws configure set aws_access_key_id  {{ secret_value }}
         aws configure set aws_secret_access_key {{ secret_value2 }}
         aws eks --region us-east-1 update-kubeconfig --name  {{CLUSTER_NAME}}
      args:
        executable: /bin/bash

    - name: Obter o nome do pod dinamicamente e executar comand
      shell: | 
        pod_name=$(kubectl get pods -n {{namespace}}  -l app=service-geolocation-api -o jsonpath='{.items[0].metadata.name}' --kubeconfig=~/.kube/config)
        kubectl exec -it $pod_name -n {{namespace}} -- {{COMAND}} ----kubeconfig=~/.kube/config
      args:
        executable: /bin/bash
      become: true
      become_user: root
    

