- name: Install apache httpd  (state=present is optional)
  hosts: all
  tasks:
   - name: teste comands
     shell: |
      echo "teste vindo da disnei" > teste.txt
    args:
      executable: /bin/bash
    