- name: Run command in pods 
  hosts: all
  tasks: 

    - name: lookup secretsmanager secret in the current region
      set_fact: 
        secret_value: "{{ lookup('aws_ssm', 'ACCESS_AWS', region='us-east-1')}}"
        secret_value2: "{{lookup('aws_ssm',  'SECRET_AWS', region='us-east-1')}}"
        
    - name: configure aws 
      shell: |
         aws configure set aws_access_key_id  {{ secret_value }}
         aws configure set aws_secret_access_key {{ secret_value2 }}
         aws eks --region us-east-1 update-kubeconfig --name  {{CLUSTER_NAME}}
      args:
        executable: /bin/bash

    - name: Obter o nome do pod dinamicamente
      k8s_facts:
        kubeconfig: /root/.kube/config 
        namespace: "{{ namespace }}"
        label_selectors:
          - "service-geolocation-api"
      register: pod_info  


    - name: Executar comando no pod
      kubernetes.core.kubectl:
          kubeconfig: "/root/.kube/config"  
          namespace: "{{namespace}}"  
          resource: pod
          name: "{{pode_info}}" 
          command: {{COMAND}}  
          stdin: no
          stdout: yes
          stderr: yes
      register: resultado_comando
     
    - name: view valor
      debug:
         var: resultado_comando

